Feature/Add dialog when clicking on the title
blockx3/imp pull request #18
Opened 2024-10-17 10:57 UTC by saadii00

2024-10-17 14:38 UTC, anisharaz requested changes

2024-10-17 14:38 UTC, anisharaz commented on apps/web/app/explore/page.tsx
>                className="m-2 p-4 bg-neutral-700 text-neutral-300 rounded-lg space-y-4"
Wrap this whole div inside the trigger.

2024-10-17 14:38 UTC, anisharaz commented on apps/web/package.json
`package.json` file is changed but the lock file is not changed , you had probability run the git commit from inside the `/apps/web/` directory. please fix this inconsistency.

2024-10-17 14:50 UTC, saadii00 commented on apps/web/package.json
I have not added the lock file by myself as it is automatically created by the build command using package.json

2024-10-17 14:50 UTC, saadii00 commented on apps/web/package.json
If you'd like me to add the lock file as well i would be happy to do that.

2024-10-17 14:56 UTC, anisharaz commented on apps/web/package.json
please add it , since it helps in package version consistency.

2024-10-17 16:00 UTC, saadii00 commented on apps/web/app/explore/page.tsx
>                className="m-2 p-4 bg-neutral-700 text-neutral-300 rounded-lg space-y-4"
Done.

2024-10-17 16:00 UTC, saadii00 commented on apps/web/package.json
Done.

2024-10-17 18:38 UTC, anisharaz requested changes

2024-10-17 18:38 UTC, anisharaz commented on pnpm-lock.yaml
Although there are no removals of package although the file has changed a lot , a lot of addition and removal are made in the lock file. There is something wrong with it , please fix this.

2024-10-18 11:17 UTC, anisharaz commented
It is resolved now

2024-10-18 11:17 UTC, closed without merging